
plugins:
  - jekyll-paginate-v2
  - jekyll-feed

# Permalinks
permalink:           pretty

# Setup
timezone:            Asia/Jakarta # eg. Asia/Kathmandu
locale:              en_us # eg. en_us
name:				 The Play Dept.
title:               The Play Dept.
tagline:             Worth Noting Music.
description:         Daily curated of worth noting music
url:                 https://www.theplaydept.com
rss:                 rss feed url
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: ''
baseurl_javascripts: '/assets/js/'
icon:                assets/images/bg-head.gif # /assets/img/icon.png [best 300px X 300px]
disqus:              disqus_shortname # get it on https://disqus.com/admin/

author:
  name:           	 The Play Dept.
  url:            	 https://www.theplaydept.com
  facebook:          theplaydept
  twitter:           theplaydept

fb_admins:           571184083005351
fb_appid:            236594396838887

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001


# Sass settings
sass:
    sass_dir: _scss
    style: :compressed

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"


pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 9

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0

  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true


 # Optional,omit or set both before and after to zero to disable.
 # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2
