backend:
  name: git-gateway
  branch: master
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
  base_url: https://api.netlify.com/auth/done
  site_domain: https://www.theplaydept.com
publish_mode: editorial_workflow
media_folder: "assets/images/posts" # Media files will be stored in the repo under assets/images
collections:
  - name: "post" # Used in routes, e.g. /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "select", options: ["playday", "playlist", "post"], default: "playday"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Artist", name: "artist", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Modifed Date", name: "last_modified_at", widget: "datetime"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Categories", name: "categories", widget: "select", options: ["playday", "playlist", "post"], default: "playday"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Youtube Video ID", name: "youtubeid", widget: "string"}
      - {label: "Post Image", name: "cover", widget: "image"}
      - {label: "Artist Website", name: "artist_website", widget: "string"}
